name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment status
      id: deployment
      with:
        token: "${{ github.token }}"
        target_url: https://madebythijmen.nl
        environment: production

    - name: Deploy to production
      uses: vitalyliber/dokku-github-action@v4.0
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        HOST: ${{ secrets.DOKKU_HOST }}
        PROJECT: ${{ secrets.DOKKU_APPLICATION }}
        FORCE_DEPLOY: true

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://madebythijmen.nl
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://madebythijmen.nl
        state: "failure"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
